CREATE TABLE "MarketingPopup" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "title" TEXT NOT NULL,
  "subtitle" TEXT,
  "body" TEXT,
  "imageUrl" TEXT,
  "backgroundColor" TEXT NOT NULL DEFAULT '#120d0a',
  "overlayColor" TEXT NOT NULL DEFAULT 'rgba(0,0,0,0.38)',
  "titleColor" TEXT NOT NULL DEFAULT '#fff7ed',
  "subtitleColor" TEXT NOT NULL DEFAULT '#fed7aa',
  "bodyColor" TEXT NOT NULL DEFAULT '#ffffff',
  "width" INTEGER NOT NULL DEFAULT 760,
  "height" INTEGER NOT NULL DEFAULT 520,
  "useImageDimensions" BOOLEAN NOT NULL DEFAULT false,
  "imageNaturalWidth" INTEGER,
  "imageNaturalHeight" INTEGER,
  "titleX" INTEGER NOT NULL DEFAULT 50,
  "titleY" INTEGER NOT NULL DEFAULT 18,
  "subtitleX" INTEGER NOT NULL DEFAULT 50,
  "subtitleY" INTEGER NOT NULL DEFAULT 30,
  "bodyX" INTEGER NOT NULL DEFAULT 50,
  "bodyY" INTEGER NOT NULL DEFAULT 58,
  "buttonsX" INTEGER NOT NULL DEFAULT 50,
  "buttonsY" INTEGER NOT NULL DEFAULT 82,
  "primaryLabel" TEXT NOT NULL DEFAULT 'Ver mas',
  "primaryAction" TEXT NOT NULL DEFAULT 'LINK',
  "primaryUrl" TEXT,
  "primaryBgColor" TEXT NOT NULL DEFAULT '#ff6a00',
  "primaryTextColor" TEXT NOT NULL DEFAULT '#111111',
  "secondaryLabel" TEXT,
  "secondaryAction" TEXT NOT NULL DEFAULT 'CLOSE',
  "secondaryUrl" TEXT,
  "secondaryBgColor" TEXT NOT NULL DEFAULT 'transparent',
  "secondaryTextColor" TEXT NOT NULL DEFAULT '#ffffff',
  "delaySeconds" INTEGER NOT NULL DEFAULT 4,
  "showOnce" BOOLEAN NOT NULL DEFAULT true,
  "isActive" BOOLEAN NOT NULL DEFAULT false,
  "startsAt" TIMESTAMP(3),
  "endsAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "MarketingPopup_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "MarketingPopup_isActive_idx" ON "MarketingPopup"("isActive");
CREATE INDEX "MarketingPopup_startsAt_idx" ON "MarketingPopup"("startsAt");
CREATE INDEX "MarketingPopup_endsAt_idx" ON "MarketingPopup"("endsAt");
